config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :albums, :images, only: :index
  end

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource  :home, only: [:show]

  root to: "home#index"
end

app/models/album.rb
class Album < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  validates_uniqueness_of :email

  def self.from_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid      = auth['uid']
      if auth['info']
        user.name = auth['info']['name'] || ""
        user.email = auth['info']['email']
      end
    end
  end
end

app/controllers/api/albums_controller.rb
class Api::AlbumsController < ApplicationController

  respond_to :json

  def index
    @user = current_user
    @albums = get_albums
  end


  private

  def get_albums
    if current_user
      response = JSON.parse(RestClient.get "https://picasaweb.google.com/data/feed/api/user/#{@user.email}?alt=json")
      response["feed"]["entry"]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid      => auth['uid'].to_s).first || User.from_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.haml
%script{ type: 'text/x-handlebars' }
  {{ outlet }}

app/views/home/show.html.haml
%h1 Home#show
%p Find me in app/views/home/show.html.haml

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SmallPicasaApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div>
    <% if current_user %>
      Signed in as <strong><%= current_user.name %></strong>
      <%= link_to "Sign out", signout_path, id: "sign_out" %>
    <% else %>
      <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
    <% end %>
  </div>

  <div>
    <%= yield %>
  </div>

</body>
</html>